### ISSUE TITLE
No support for utf-8

### ISSUE THREAD

**Issue by raphaelgoetter** [jeanfredrik/css-info#1]
Hello,

It seems that css-info doesn't parse the file when a "special" character occurs : https://css-info.jeanfredrik.com/?url=https%3A%2F%2Fcdn.alsacreations.net%2Fcss%2Fstyles.1495007953.min.css

Have a nice day!

**Comment by jeanfredrik** [comment]
This issue should be posted to the [jeanfredrik/css-info-app](https://github.com/jeanfredrik/css-info-app) repo. Can you please create the same issue there?

I’m sorry for the confusing naming. This is an older version that’s now superseded by *css-info-app*, which is running at https://css-info.jeanfredrik.com/
